name: Review Assign

on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: hkusu/review-assign-action@v1
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          assignees: ${{ github.actor }}
          reviewers: gyoyeon-kim, ozen0718, doctor-taco
